# No time to vet. Source: https://github.com/marketplace/actions/ftp-deploy
# on: push

on:
  pull_request:
    branches: [ null ]

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.fh }}
        username: ${{ secrets.fu }}
        password: ${{ secrets.fp }}
